{
 "title": "IoT Sensors Dashboard",
 "tags": [
  "iot",
  "sensors"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"sensors\")\n  |> filter(fn: (r) => r._field == \"temperature\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Device Status",
   "type": "table",
   "gridPos": { "h": 11, "w": 9, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"iotsensors\")\n  |> range(start: -30d)\n  |> filter(fn: (r) => r._measurement == \"devices\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> filter(fn: (r) => r.topic =~ /status$/)\n  |> group(columns: [\"deviceid\"])\n  |> last()\n  |> group()\n  |> keep(columns: [\"_time\", \"deviceid\", \"_value\"])\n  |> rename(columns: {_time: \"Updated\", deviceid: \"Device ID\", _value: \"Status\"})\n\n\n"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"sensors\")\n  |> filter(fn: (r) => r._field == \"humidity\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)"
    }
   ]
  },
  {
   "title": "LastSeen",
   "type": "table",
   "gridPos": { "h": 11, "w": 9, "x": 12, "y": 11 },
   "targets": [
    {
     "query": "from(bucket: \"iotsensors\")\r\n  |> range(start: -30d)\r\n  |> filter(fn: (r) => r._measurement == \"devices\")\r\n  |> filter(fn: (r) => r._field == \"value\")\r\n  |> filter(fn: (r) => r.topic =~ /status$/)\r\n  |> group(columns: [\"deviceid\"])\r\n  |> last()\r\n  |> group()\r\n  |> map(fn: (r) => ({\r\n      deviceid: r.deviceid,\r\n      seconds_ago: float(v: uint(v: now()) - uint(v: r._time)) / 1000000000.0\r\n    }))\r\n  |> keep(columns: [\"deviceid\", \"seconds_ago\"])\r\n  |> rename(columns: {deviceid: \"Device ID\", seconds_ago: \"Seconds ago\"})"
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"sensors\")\n  |> filter(fn: (r) => r._field == \"pressure\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)"
    }
   ]
  }
 ]
}